/*
MySQL Data Transfer
Source Host: 206.221.251.17
Source Database: epg_preview
Target Host: 206.221.251.17
Target Database: epg_preview
Date: 2014/3/18 15:26:30
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for EPG_REL_CONTENT
-- ----------------------------
DROP TABLE IF EXISTS `EPG_REL_CONTENT`;
CREATE TABLE `EPG_REL_CONTENT` (
  `ID` bigint(20) NOT NULL,
  `REL_NAME` varchar(256) NOT NULL COMMENT '包名',
  `REL_CODE` varchar(128) NOT NULL COMMENT '包code',
  `CONTENT_CODE` varchar(128) NOT NULL COMMENT 'contentCode',
  `VIDEO_TYPE` int(2) DEFAULT NULL COMMENT '视频类型:0(HD),1(SD),2(3D)',
  `BODY_TYPE` int(2) DEFAULT NULL COMMENT '内容类型:1(正片),2(预告片),3(片花)',
  `AUDIO_TYPE` int(2) DEFAULT NULL COMMENT '声音类型:1(原声),2(国语),3(粤语)',
  `STATUS` int(2) DEFAULT '0' COMMENT '0(正常),1(删除)',
  `TYPE` varchar(50) DEFAULT NULL COMMENT '剧集:单剧集(vod),多剧集(series)',
  `REL_CODE_FLAG` int(2) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `REL_CODE` (`REL_CODE`),
  KEY `STATUS` (`STATUS`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
-- ----------------------------
-- Table structure for EPG_SUBJECT_PAGE
-- ----------------------------
ALTER TABLE EPG_SUBJECT_PAGE ADD `POSTER` varchar(128) DEFAULT NULL, ADD `STILL` varchar(128) DEFAULT NULL, ADD `ICON` varchar(128) DEFAULT NULL;
-- ----------------------------
-- Table structure for EPG_CONTENT_EPISODE
-- ----------------------------
ALTER TABLE EPG_CONTENT_EPISODE ADD `STATUS` int(11) DEFAULT NULL, ADD `EXCUTE_TIME` datetime DEFAULT NULL, ADD `TITLE` varchar(128) DEFAULT NULL;
-- ----------------------------
-- Table structure for EPG_CONTENT_PROGRAM 如果数据库表中已有HD_TYPE则不要ADD
-- ----------------------------
ALTER TABLE EPG_CONTENT_PROGRAM ADD `REL_CODE` varchar(128) DEFAULT NULL;
-- ----------------------------
-- Table structure for EPG_CONTENT_SERIES 如果数据库表中已有HD_TYPE则不要ADD
-- ----------------------------
ALTER TABLE EPG_CONTENT_SERIES ADD `REL_CODE` varchar(128) DEFAULT NULL;
-- ----------------------------
-- Table structure for CONTENT_WITH_PIC 如果数据库表中已有HD_TYPE则不要ADD
-- ----------------------------
ALTER TABLE CONTENT_WITH_PIC ADD `HD_TYPE` int(11) DEFAULT '0', ADD `REL_CODE` varchar(128) DEFAULT NULL;
-- ----------------------------
-- Trigger structure for INSERT_PROGRAM_TRIGGER
-- ----------------------------
DROP TRIGGER INSERT_PROGRAM_TRIGGER;
DELIMITER ;;
CREATE TRIGGER `INSERT_PROGRAM_TRIGGER` AFTER INSERT ON `EPG_CONTENT_PROGRAM` FOR EACH ROW BEGIN
INSERT INTO CONTENT_WITH_PIC(`CONTENT_ID`, `CONTENT_CODE`, `TITLE`, `TITLE_BRIEF`, `ENABLE_STATUS`, `COUNTRY_OF_ORIGIN`, `YEAR`, `VOD_DUB`, `VOD_CAPTION`, `DIRECTOR`, `ACTORS`, `SUMMARY_MEDIUM`, `SUMMARY_SHORT`, `KEY_WORD`, `REMARK`, `PROGRAM_LEVEL`, `RESERVE1`, `CREATION_DATE`, `POSTER`, `STILL`, `ICON`, `EPISODE_NUMBER`, `SEARCH_NAME`, `RUN_TIME`, `DISPLAY_RUN_TIME`, `CONTENT_TYPE`, `PROGRAM_TYPE`, `PROVIDER`, `PRODUCT`, `SUGGESTED_PRICE`, `TITLE_TYPE`, `ASSETID`, `TAGS`, `MAIN_FOLDER`, `HD_TYPE`, `REL_CODE`) VALUES(NEW.CONTENT_ID,NEW.CONTENT_CODE,NEW.TITLE,NEW.TITLE_BRIEF,NEW.ENABLE_STATUS,NEW.COUNTRY_OF_ORIGIN,NEW.YEAR,NEW.VOD_DUB,NEW.VOD_CAPTION,NEW.DIRECTOR,NEW.ACTORS,NEW.SUMMARY_MEDIUM,NEW.SUMMARY_SHORT,NEW.KEY_WORD,NEW.REMARK,NEW.PROGRAM_LEVEL,NEW.RESERVE1,NEW.CREATION_DATE,NEW.POSTER,NEW.STILL,NEW.ICON,1,NEW.SEARCH_NAME,NEW.RUN_TIME,NEW.DISPLAY_RUN_TIME,'VOD',NEW.TYPE,NEW.PROVIDER,NEW.PRODUCT,NEW.SUGGESTED_PRICE,NEW.TITLE_TYPE,NEW.ASSETID,NEW.TAGS,NEW.MAIN_FOLDER,NEW.HD_TYPE,NEW.REL_CODE );
 
END;;
DELIMITER ;
-- ----------------------------
-- Trigger structure for UPDATE_PROGRAM_TRIGGER
-- ----------------------------
DROP TRIGGER UPDATE_PROGRAM_TRIGGER;
DELIMITER ;;
CREATE TRIGGER `UPDATE_PROGRAM_TRIGGER` AFTER UPDATE ON `EPG_CONTENT_PROGRAM` FOR EACH ROW BEGIN
UPDATE CONTENT_WITH_PIC SET `CONTENT_CODE`=NEW.CONTENT_CODE, `TITLE`=NEW.TITLE, `TITLE_BRIEF`=NEW.TITLE_BRIEF, `ENABLE_STATUS`=NEW.ENABLE_STATUS, `COUNTRY_OF_ORIGIN`=NEW.COUNTRY_OF_ORIGIN, `YEAR`=NEW.YEAR, `VOD_DUB`=NEW.VOD_DUB, `VOD_CAPTION`=NEW.VOD_CAPTION, `DIRECTOR`=NEW.DIRECTOR, `ACTORS`=NEW.ACTORS, `SUMMARY_MEDIUM`=NEW.SUMMARY_MEDIUM, `SUMMARY_SHORT`=NEW.SUMMARY_SHORT, `KEY_WORD`=NEW.KEY_WORD, `REMARK`=NEW.REMARK, `PROGRAM_LEVEL`=NEW.PROGRAM_LEVEL, `RESERVE1`=NEW.RESERVE1, `CREATION_DATE`=NEW.CREATION_DATE, `POSTER`=NEW.POSTER, `STILL`=NEW.STILL, `ICON`=NEW.ICON, `EPISODE_NUMBER`=1, `SEARCH_NAME`=NEW.SEARCH_NAME, `RUN_TIME`=NEW.RUN_TIME, `DISPLAY_RUN_TIME`=NEW.DISPLAY_RUN_TIME, `CONTENT_TYPE`='VOD', `PROGRAM_TYPE`=NEW.TYPE, `PROVIDER`=NEW.PROVIDER, `PRODUCT`=NEW.PRODUCT, `SUGGESTED_PRICE`=NEW.SUGGESTED_PRICE, `TITLE_TYPE`=NEW.TITLE_TYPE, `ASSETID`=NEW.ASSETID, `TAGS`=NEW.TAGS, `MAIN_FOLDER`=NEW.MAIN_FOLDER, `HD_TYPE`=NEW.HD_TYPE, `REL_CODE`=NEW.REL_CODE WHERE `CONTENT_ID` = NEW.CONTENT_ID;

END;;
DELIMITER ;
-- ----------------------------
-- Trigger structure for INSERT_SERIES_TRIGGER
-- ----------------------------
DROP TRIGGER INSERT_SERIES_TRIGGER;
DELIMITER ;;
CREATE TRIGGER `INSERT_SERIES_TRIGGER` AFTER INSERT ON `EPG_CONTENT_SERIES` FOR EACH ROW BEGIN
INSERT INTO CONTENT_WITH_PIC(`CONTENT_ID`, `CONTENT_CODE`, `TITLE`, `TITLE_BRIEF`, `ENABLE_STATUS`, `COUNTRY_OF_ORIGIN`, `YEAR`, `VOD_DUB`, `VOD_CAPTION`, `DIRECTOR`, `ACTORS`, `SUMMARY_MEDIUM`, `SUMMARY_SHORT`, `KEY_WORD`, `REMARK`, `PROGRAM_LEVEL`, `RESERVE1`, `CREATION_DATE`, `POSTER`, `STILL`, `ICON`, `EPISODE_NUMBER`, `SEARCH_NAME`, `RUN_TIME`, `DISPLAY_RUN_TIME`, `CONTENT_TYPE`, `PROGRAM_TYPE`, `PROVIDER`, `PRODUCT`, `SUGGESTED_PRICE`, `TITLE_TYPE`, `TAGS`, `MAIN_FOLDER`, `HD_TYPE`, `REL_CODE`) VALUES(NEW.CONTENT_ID,NEW.CONTENT_CODE,NEW.TITLE,NEW.TITLE_BRIEF,NEW.ENABLE_STATUS,NEW.COUNTRY_OF_ORIGIN,NEW.YEAR,NEW.VOD_DUB,NEW.VOD_CAPTION,NEW.DIRECTOR,NEW.ACTORS,NEW.SUMMARY_MEDIUM,NEW.SUMMARY_SHORT,NEW.KEY_WORD,NEW.REMARK,NEW.PROGRAM_LEVEL,NEW.RESERVE1,NEW.CREATION_DATE,NEW.POSTER,NEW.STILL,NEW.ICON,NEW.EPISODE_NUMBER,NEW.SEARCH_NAME,NULL,NULL,'SERIES','SERIES',NEW.PROVIDER,NULL,0,'VOD',NEW.TAGS,NEW.MAIN_FOLDER,NEW.HD_TYPE,NEW.REL_CODE);
 
END;;
DELIMITER ;
-- ----------------------------
-- Trigger structure for UPDATE_SERIES_TRIGGER
-- ----------------------------
DROP TRIGGER UPDATE_SERIES_TRIGGER;
DELIMITER ;;
CREATE TRIGGER `UPDATE_SERIES_TRIGGER` AFTER UPDATE ON `EPG_CONTENT_SERIES` FOR EACH ROW BEGIN
UPDATE CONTENT_WITH_PIC SET `CONTENT_CODE`=NEW.CONTENT_CODE, `TITLE`=NEW.TITLE, `TITLE_BRIEF`=NEW.TITLE_BRIEF, `ENABLE_STATUS`=NEW.ENABLE_STATUS, `COUNTRY_OF_ORIGIN`=NEW.COUNTRY_OF_ORIGIN, `YEAR`=NEW.YEAR, `VOD_DUB`=NEW.VOD_DUB, `VOD_CAPTION`=NEW.VOD_CAPTION, `DIRECTOR`=NEW.DIRECTOR, `ACTORS`=NEW.ACTORS, `SUMMARY_MEDIUM`=NEW.SUMMARY_MEDIUM, `SUMMARY_SHORT`=NEW.SUMMARY_SHORT, `KEY_WORD`=NEW.KEY_WORD, `REMARK`=NEW.REMARK, `PROGRAM_LEVEL`=NEW.PROGRAM_LEVEL, `RESERVE1`=NEW.RESERVE1, `CREATION_DATE`=NEW.CREATION_DATE, `POSTER`=NEW.POSTER, `STILL`=NEW.STILL, `ICON`=NEW.ICON, `EPISODE_NUMBER`=NEW.EPISODE_NUMBER, `SEARCH_NAME`=NEW.SEARCH_NAME, `RUN_TIME`=NULL, `DISPLAY_RUN_TIME`=NULL, `CONTENT_TYPE`='SERIES', `PROGRAM_TYPE`='SERIES', `PROVIDER`=NEW.PROVIDER, `PRODUCT`=NULL, `SUGGESTED_PRICE`=0, `TITLE_TYPE`='VOD', `TAGS`=NEW.TAGS, `MAIN_FOLDER`=NEW.MAIN_FOLDER, `HD_TYPE`=NEW.HD_TYPE, `REL_CODE`=NEW.REL_CODE  WHERE `CONTENT_ID` = NEW.CONTENT_ID;
 
END;;
DELIMITER ;
-- ----------------------------
-- EPG_CONTENT_EPISODE字段STATUS、EXCUTE_TIME初始化
-- ----------------------------
UPDATE EPG_CONTENT_EPISODE SET STATUS = 1 WHERE STATUS is NULL OR STATUS = 0;
UPDATE EPG_CONTENT_EPISODE SET EXCUTE_TIME = now() WHERE EXCUTE_TIME IS NULL;