/*
Navicat MySQL Data Transfer

Source Server         : RuGao_Master_VPN
Source Server Version : 50152
Source Host           : 206.222.5.17:3306
Source Database       : epg_preview_3d

Target Server Type    : MYSQL
Target Server Version : 50152
File Encoding         : 65001

Date: 2014-06-11 14:54:30
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for CONTENT_WITH_PIC
-- ----------------------------
DROP TABLE IF EXISTS `CONTENT_WITH_PIC`;
CREATE TABLE `CONTENT_WITH_PIC` (
  `CONTENT_ID` bigint(20) NOT NULL,
  `CONTENT_CODE` varchar(128) NOT NULL,
  `TITLE` varchar(256) DEFAULT NULL,
  `TITLE_BRIEF` varchar(256) DEFAULT NULL,
  `ENABLE_STATUS` int(11) DEFAULT NULL,
  `COUNTRY_OF_ORIGIN` varchar(64) DEFAULT NULL,
  `YEAR` varchar(4) DEFAULT NULL,
  `VOD_DUB` varchar(64) DEFAULT NULL,
  `VOD_CAPTION` varchar(64) DEFAULT NULL,
  `DIRECTOR` varchar(128) DEFAULT NULL,
  `ACTORS` varchar(128) DEFAULT NULL,
  `SUMMARY_MEDIUM` varchar(1024) DEFAULT NULL,
  `SUMMARY_SHORT` varchar(1024) DEFAULT NULL,
  `KEY_WORD` varchar(256) DEFAULT NULL,
  `REMARK` varchar(512) DEFAULT NULL,
  `PROGRAM_LEVEL` int(11) DEFAULT NULL,
  `RESERVE1` varchar(128) DEFAULT NULL,
  `CREATION_DATE` date DEFAULT NULL,
  `POSTER` varchar(512) DEFAULT NULL,
  `STILL` varchar(512) DEFAULT NULL,
  `ICON` varchar(512) DEFAULT NULL,
  `EPISODE_NUMBER` bigint(11) DEFAULT NULL,
  `SEARCH_NAME` varchar(128) DEFAULT NULL,
  `RUN_TIME` varchar(8) DEFAULT NULL,
  `DISPLAY_RUN_TIME` varchar(8) DEFAULT NULL,
  `CONTENT_TYPE` varchar(6) DEFAULT NULL,
  `PROGRAM_TYPE` varchar(128) DEFAULT NULL,
  `PROVIDER` varchar(64) DEFAULT NULL,
  `PRODUCT` varchar(32) DEFAULT NULL,
  `SUGGESTED_PRICE` bigint(20) DEFAULT NULL,
  `TITLE_TYPE` varchar(128) DEFAULT NULL,
  `TAGS` varchar(128) DEFAULT NULL,
  `ASSETID` varchar(256) DEFAULT NULL,
  `MAIN_FOLDER` varchar(64) DEFAULT NULL,
  `SUB_FOLDER` varchar(64) DEFAULT NULL,
  `HD_TYPE` int(11) DEFAULT '0',
  `REL_CODE` varchar(128) DEFAULT NULL,
  KEY `VIEWCONTENTCODEINDEX` (`CONTENT_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of CONTENT_WITH_PIC
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_AD_PUTTING
-- ----------------------------
DROP TABLE IF EXISTS `EPG_AD_PUTTING`;
CREATE TABLE `EPG_AD_PUTTING` (
  `ID` bigint(20) NOT NULL,
  `CATEGORY_ID` bigint(20) NOT NULL COMMENT '栏目标识',
  `CATEGORY_CODE` varchar(128) NOT NULL COMMENT '栏目编码',
  `PUTTING` int(2) DEFAULT NULL COMMENT '是否投放：RN            0：不投放RN            1：投放',
  `PROPERTY` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ADCATEGORYCODEINDEX` (`CATEGORY_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='广告配置表';

-- ----------------------------
-- Records of EPG_AD_PUTTING
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_BUSINESS
-- ----------------------------
DROP TABLE IF EXISTS `EPG_BUSINESS`;
CREATE TABLE `EPG_BUSINESS` (
  `ID` bigint(20) NOT NULL,
  `NAME` varchar(128) DEFAULT NULL,
  `CODE` varchar(128) DEFAULT NULL,
  `TITLE` varchar(128) DEFAULT NULL,
  `SUB_TITLE` varchar(128) DEFAULT NULL,
  `TYPE` varchar(32) DEFAULT NULL,
  `STATUS` int(4) DEFAULT NULL,
  `GENRE` varchar(128) DEFAULT NULL,
  `VALID_TIME` datetime DEFAULT NULL,
  `EXPIRE_TIME` datetime DEFAULT NULL,
  `BUSINESS_ICON` varchar(256) DEFAULT NULL,
  `DESCRIPTION` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `BUSINESSCODEINDEX` (`CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of EPG_BUSINESS
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CATEGORY
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CATEGORY`;
CREATE TABLE `EPG_CATEGORY` (
  `ID` bigint(20) NOT NULL,
  `NAME` varchar(128) NOT NULL,
  `TITLE` varchar(64) NOT NULL,
  `CODE` varchar(128) NOT NULL,
  `ACTIVE_STATUS` int(2) NOT NULL DEFAULT '0' COMMENT '0：失效RN            1：生效',
  `CHILD_INDEX` int(8) DEFAULT NULL,
  `PARENT_CODE` varchar(128) DEFAULT NULL,
  `LOCATE_STRING` varchar(256) NOT NULL,
  `CATEGORY_ICON` varchar(128) DEFAULT NULL,
  `BACKGROUND` varchar(128) DEFAULT NULL,
  `DESCRIPTION` varchar(1024) DEFAULT NULL,
  `SERVICE_TYPES` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CATEGORYCODEINDEX` (`CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of EPG_CATEGORY
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CATEGORY_ITEM
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CATEGORY_ITEM`;
CREATE TABLE `EPG_CATEGORY_ITEM` (
  `ID` bigint(20) NOT NULL,
  `CATEGORY_CODE` varchar(128) NOT NULL,
  `ITEM_TYPE` varchar(64) NOT NULL,
  `ITEM_CODE` varchar(128) NOT NULL,
  `TITLE` varchar(256) DEFAULT NULL,
  `SUB_TITLE` varchar(128) DEFAULT NULL,
  `STATUS` int(2) NOT NULL COMMENT '-1：已删除RN            0：可见RN            1：不可见',
  `TYPE` int(2) DEFAULT NULL COMMENT '0：普通RN            1：置顶',
  `SHOW_FLAG` int(2) DEFAULT NULL COMMENT '1： 火RN            2： 热 RN            3： 新 ',
  `ITEM_ORDER` int(8) DEFAULT NULL,
  `BEGIN_TIME` datetime DEFAULT NULL,
  `END_TIME` datetime DEFAULT NULL,
  `VALID_TIME` datetime DEFAULT NULL,
  `EXPIRE_TIME` datetime DEFAULT NULL,
  `ITEM_ICON` varchar(256) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `PROGRAM_LEVEL` varchar(10) DEFAULT NULL COMMENT '评分',
  `COMMENTS_NUM` int(10) DEFAULT NULL COMMENT '评论数',
  PRIMARY KEY (`ID`),
  KEY `ITEMCATEGORYCODEINDEX` (`CATEGORY_CODE`),
  KEY `ITEMCODEINDEX` (`ITEM_CODE`),
  KEY `VALIDTIMEINDEX` (`VALID_TIME`),
  KEY `EXPIRETIMEINDEX` (`EXPIRE_TIME`),
  KEY `CATEGORY_CODE` (`CATEGORY_CODE`,`ITEM_CODE`,`STATUS`,`VALID_TIME`,`EXPIRE_TIME`),
  KEY `CATEGORY_CODE_2` (`CATEGORY_CODE`,`STATUS`,`VALID_TIME`,`EXPIRE_TIME`),
  KEY `STATUS` (`STATUS`),
  KEY `PROGRAM_LEVEL` (`PROGRAM_LEVEL`,`COMMENTS_NUM`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of EPG_CATEGORY_ITEM
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CHANNEL_PARAM
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CHANNEL_PARAM`;
CREATE TABLE `EPG_CHANNEL_PARAM` (
  `ID` bigint(20) NOT NULL,
  `CHANNEL_ID` bigint(20) DEFAULT NULL,
  `CHANNEL_CODE` varchar(128) NOT NULL,
  `CHANNEL_NUMBER` int(4) DEFAULT NULL,
  `NETWORK_ID` varchar(32) DEFAULT NULL,
  `CASYSTEM_ID` varchar(32) DEFAULT NULL,
  `ECM_PID` varchar(32) DEFAULT NULL,
  `VIDEO_PID` varchar(64) DEFAULT NULL,
  `VIDEO_TYPE` varchar(16) DEFAULT NULL COMMENT '视频类型包括：RN            MP1VRN            MP2VRN            MP4VRN            H264RN            VCL',
  `AUDIO_PID` varchar(64) DEFAULT NULL,
  `AUDIO_TYPE` varchar(16) DEFAULT NULL COMMENT '音频类型包括：RN            MP1ARN            MP2ARN            MP4ARN            AC3RN            AACRN            WMARN            MP3',
  `PCR_PID` varchar(32) DEFAULT NULL,
  `FREQ` bigint(12) DEFAULT NULL COMMENT '频率，单位HZ',
  `SYM` bigint(12) DEFAULT NULL COMMENT '符号率，单位：SYMBOL/S',
  `MOD_TYPE` int(8) DEFAULT NULL COMMENT 'QAM调制方式',
  `SERVICE_ID` varchar(32) DEFAULT NULL COMMENT '服务标识',
  `TRANSPORT_ID` varchar(32) DEFAULT NULL COMMENT '码流标识',
  PRIMARY KEY (`ID`),
  KEY `CHANNELCODEPARAMINDEX` (`CHANNEL_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='直播频道配置参数';

-- ----------------------------
-- Records of EPG_CHANNEL_PARAM
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CONTENT_CHANNEL
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CONTENT_CHANNEL`;
CREATE TABLE `EPG_CONTENT_CHANNEL` (
  `CONTENT_ID` bigint(20) NOT NULL COMMENT '记录标识',
  `CONTENT_CODE` varchar(128) NOT NULL COMMENT '内容编码',
  `TITLE` varchar(128) NOT NULL COMMENT '显示标题',
  `TITLE_BRIEF` varchar(64) NOT NULL COMMENT '显示标题',
  `PROVIDER` varchar(64) DEFAULT NULL COMMENT '提供商',
  `PROVIDER_ID` varchar(32) DEFAULT NULL COMMENT '提供商标识',
  `CREATION_DATE` date DEFAULT NULL COMMENT '入库日期',
  `RESERVE5` varchar(512) DEFAULT NULL,
  `RESERVE4` varchar(256) DEFAULT NULL,
  `RESERVE3` varchar(256) DEFAULT NULL,
  `RESERVE2` varchar(128) DEFAULT NULL,
  `RESERVE1` varchar(128) DEFAULT NULL,
  `SERVICE_NAME` varchar(128) DEFAULT NULL,
  `PLAY_URL` varchar(256) DEFAULT NULL,
  `LIVE_CODE` varchar(32) DEFAULT NULL,
  `CHANNEL_NUM` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`CONTENT_ID`),
  KEY `CHANNELCODEINDEX` (`CONTENT_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='直播频道表';

-- ----------------------------
-- Records of EPG_CONTENT_CHANNEL
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CONTENT_EPISODE
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CONTENT_EPISODE`;
CREATE TABLE `EPG_CONTENT_EPISODE` (
  `ID` bigint(20) NOT NULL,
  `EPISODE_INDEX` int(8) NOT NULL,
  `CONTENT_ID` bigint(20) NOT NULL,
  `SERIES_ID` bigint(20) NOT NULL,
  `CONTENT_CODE` varchar(128) NOT NULL,
  `SERIES_CODE` varchar(128) NOT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `EXCUTE_TIME` datetime DEFAULT NULL,
  `TITLE` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SERIESCODEEPISODEINDEX` (`SERIES_CODE`),
  KEY `SERIES_ID` (`SERIES_ID`),
  KEY `CONTENT_CODE` (`CONTENT_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='连续剧剧集表';

-- ----------------------------
-- Records of EPG_CONTENT_EPISODE
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CONTENT_LABEL
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CONTENT_LABEL`;
CREATE TABLE `EPG_CONTENT_LABEL` (
  `ID` bigint(20) NOT NULL,
  `CONTENT_CODE` varchar(128) NOT NULL,
  `USER_ID` varchar(128) NOT NULL,
  `EPISODE_INDEX` int(8) NOT NULL DEFAULT '0',
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `LABELINDEX` (`USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='用于记录当前用户观看连续剧的集数';

-- ----------------------------
-- Records of EPG_CONTENT_LABEL
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CONTENT_LIVE
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CONTENT_LIVE`;
CREATE TABLE `EPG_CONTENT_LIVE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EVENT_ID` int(10) DEFAULT NULL,
  `NAME` varchar(256) DEFAULT NULL,
  `DESCRIPTION` varchar(512) DEFAULT NULL,
  `BEGIN_TIME` datetime DEFAULT NULL,
  `END_TIME` datetime DEFAULT NULL,
  `DURATION` varchar(128) DEFAULT NULL,
  `CREATION_TIME` datetime DEFAULT NULL,
  `SCHEDULE_DATE` datetime DEFAULT NULL,
  `CHANNEL_CODE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='直播节目单';

-- ----------------------------
-- Records of EPG_CONTENT_LIVE
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CONTENT_MARK
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CONTENT_MARK`;
CREATE TABLE `EPG_CONTENT_MARK` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONTENT_TYPE` varchar(64) NOT NULL,
  `CONTENT_CODE` varchar(128) NOT NULL,
  `GOOD_COUNT` bigint(11) NOT NULL DEFAULT '0',
  `BAD_COUNT` bigint(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `MARKCONTENTCODEINDEX` (`CONTENT_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='记录用户对内容进行顶踩的统计';

-- ----------------------------
-- Records of EPG_CONTENT_MARK
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CONTENT_MEDIA
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CONTENT_MEDIA`;
CREATE TABLE `EPG_CONTENT_MEDIA` (
  `ID` bigint(20) NOT NULL,
  `CONTENT_ID` bigint(20) NOT NULL COMMENT '内容标识',
  `CONTENT_CODE` varchar(128) DEFAULT NULL COMMENT '内容编码',
  `TYPE` varchar(16) NOT NULL COMMENT 'MOVIE:正片RN            PREVIEW:预览片',
  `AUDIO_TYPE` varchar(16) DEFAULT NULL COMMENT '音频类型',
  `FILE_SIZE` bigint(20) DEFAULT NULL COMMENT '文件大小',
  `CHECKSUM` varchar(64) DEFAULT NULL COMMENT '校验码',
  `FILE_NAME` varchar(256) DEFAULT NULL COMMENT '文件名',
  `FORMAT` varchar(64) DEFAULT NULL COMMENT '编码格式',
  `BITRATE` varchar(64) DEFAULT NULL COMMENT '码流',
  `HIGN_DEFITION` int(2) DEFAULT NULL COMMENT '1：高清RN            0：不是高清',
  `RESERVE1` varchar(128) DEFAULT NULL COMMENT '保留字段1',
  `RESERVE2` varchar(128) DEFAULT NULL COMMENT '保留字段2',
  `RESERVE3` varchar(256) DEFAULT NULL COMMENT '保留字段3',
  `RESERVE4` varchar(256) DEFAULT NULL COMMENT '保留字段4',
  `RESERVE5` varchar(512) DEFAULT NULL COMMENT '保留字段5',
  `ASSET_ID` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `MEDIACONTENTCODEINDEX` (`CONTENT_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='内容媒体文件表';

-- ----------------------------
-- Records of EPG_CONTENT_MEDIA
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CONTENT_OFFERING
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CONTENT_OFFERING`;
CREATE TABLE `EPG_CONTENT_OFFERING` (
  `ID` bigint(20) NOT NULL COMMENT 'ID',
  `OFFERING_ID` varchar(128) DEFAULT NULL COMMENT 'OFFERINGID',
  `CONTENT_CODE` varchar(128) DEFAULT NULL COMMENT '内容编码',
  `SERVICE_TYPE` varchar(64) DEFAULT NULL COMMENT '服务类型',
  `SERVICE_NAME` varchar(128) DEFAULT NULL COMMENT '服务名称',
  `SERVICE_CODE` varchar(128) DEFAULT NULL COMMENT '服务编码',
  `SUGGESTED_PRICE` int(8) DEFAULT NULL COMMENT '建议价格',
  `PRICE` int(8) DEFAULT NULL COMMENT '使用价格',
  `RENTAL_DURATION` int(8) DEFAULT NULL COMMENT 'RENTAL周期',
  `RESERVE1` varchar(64) DEFAULT NULL,
  `RESERVE2` varchar(64) DEFAULT NULL,
  `RESERVE3` varchar(128) DEFAULT NULL,
  `RESERVE4` varchar(128) DEFAULT NULL,
  `RESERVE5` varchar(256) DEFAULT NULL,
  `URL` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CONTENT_CODE` (`CONTENT_CODE`),
  KEY `SERVICE_TYPE` (`SERVICE_TYPE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='OFFERING表';

-- ----------------------------
-- Records of EPG_CONTENT_OFFERING
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CONTENT_PROGRAM
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CONTENT_PROGRAM`;
CREATE TABLE `EPG_CONTENT_PROGRAM` (
  `CONTENT_ID` bigint(20) NOT NULL COMMENT '记录标识',
  `CONTENT_CODE` varchar(128) DEFAULT NULL,
  `TITLE` varchar(256) DEFAULT NULL COMMENT '显示标题',
  `TITLE_BRIEF` varchar(256) DEFAULT NULL,
  `PROVIDER` varchar(64) DEFAULT NULL COMMENT '提供商',
  `RATING` varchar(10) DEFAULT NULL COMMENT '影片分级',
  `RUN_TIME` varchar(8) DEFAULT NULL COMMENT '播出时长',
  `DISPLAY_RUN_TIME` varchar(8) DEFAULT NULL COMMENT '显示时长',
  `MAXIMUM_VIEWING_LENGTH` varchar(10) DEFAULT NULL COMMENT '最大播出时长',
  `PREVIEW_PERIOD` varchar(8) DEFAULT NULL COMMENT '预览片段时长',
  `BILLING_ID` varchar(16) DEFAULT NULL COMMENT '计费标识',
  `PRODUCT` varchar(32) DEFAULT NULL COMMENT '产品标识',
  `SUGGESTED_PRICE` int(8) DEFAULT NULL COMMENT '建议价格，单位：分',
  `COUNTRY_OF_ORIGIN` varchar(64) DEFAULT NULL COMMENT '发行国家',
  `YEAR` varchar(4) DEFAULT NULL COMMENT '发行年份',
  `STUDIO` varchar(128) DEFAULT NULL COMMENT '发行公司',
  `PRODUCERS` varchar(128) DEFAULT NULL COMMENT '制片',
  `ACTORS` varchar(128) DEFAULT NULL COMMENT '演员',
  `DIRECTOR` varchar(128) DEFAULT NULL COMMENT '导演',
  `WRITER` varchar(128) DEFAULT NULL COMMENT '编剧',
  `TAGS` varchar(1024) DEFAULT NULL,
  `SUMMARY_MEDIUM` varchar(1024) DEFAULT NULL COMMENT '内容简介',
  `SUMMARY_SHORT` varchar(1024) DEFAULT NULL COMMENT '内容看点',
  `CREATION_DATE` date DEFAULT NULL COMMENT '入库日期',
  `COURTYARD` varchar(256) DEFAULT NULL COMMENT '院线信息',
  `PROGRAM_LEVEL` int(2) DEFAULT NULL COMMENT '评分',
  `VOD_DUB` varchar(64) DEFAULT NULL COMMENT '配音',
  `VOD_CAPTION` varchar(64) DEFAULT NULL COMMENT '字幕',
  `KEY_WORD` varchar(256) DEFAULT NULL COMMENT '关键字',
  `REMARK` varchar(512) DEFAULT NULL COMMENT '备注',
  `RESERVE1` varchar(128) DEFAULT NULL,
  `RESERVE2` varchar(128) DEFAULT NULL,
  `RESERVE3` varchar(256) DEFAULT NULL,
  `RESERVE4` varchar(256) DEFAULT NULL,
  `RESERVE5` varchar(512) DEFAULT NULL,
  `OFFERING_ID` varchar(128) DEFAULT NULL,
  `SERVICE_TYPE` varchar(64) DEFAULT NULL,
  `SERVICE_NAME` varchar(128) DEFAULT NULL,
  `POSTER` varchar(512) DEFAULT NULL,
  `STILL` varchar(512) DEFAULT NULL,
  `ICON` varchar(512) DEFAULT NULL,
  `ENABLE_STATUS` int(2) DEFAULT NULL COMMENT '可用状态',
  `SERVICE_CODE` varchar(128) DEFAULT NULL,
  `TYPE` varchar(64) DEFAULT NULL,
  `SEARCH_NAME` varchar(64) DEFAULT NULL,
  `TITLE_TYPE` varchar(64) DEFAULT NULL,
  `PROVIDER_ID` varchar(32) DEFAULT NULL,
  `MAIN_FOLDER` varchar(64) DEFAULT NULL,
  `SUB_FOLDER` varchar(64) DEFAULT NULL,
  `HD_TYPE` int(11) DEFAULT NULL,
  `ASSETID` varchar(256) DEFAULT NULL,
  `REL_CODE` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`CONTENT_ID`),
  KEY `PROGRAMCODEINDEX` (`CONTENT_CODE`),
  KEY `SEARCHNAMEINDEX` (`SEARCH_NAME`),
  KEY `TITLE` (`TITLE`),
  KEY `TITLE_TYPE` (`TITLE_TYPE`),
  KEY `TYPE` (`TYPE`),
  KEY `ENABLE_STATUS` (`ENABLE_STATUS`),
  KEY `SEARCH_NAME` (`SEARCH_NAME`),
  KEY `ASSETID` (`ASSETID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='节目表';

-- ----------------------------
-- Records of EPG_CONTENT_PROGRAM
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CONTENT_SCHEDULE
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CONTENT_SCHEDULE`;
CREATE TABLE `EPG_CONTENT_SCHEDULE` (
  `ID` bigint(20) NOT NULL,
  `CHANNEL_CODE` varchar(128) NOT NULL,
  `NAME` varchar(256) NOT NULL,
  `CODE` varchar(128) DEFAULT NULL,
  `BEGIN_TIME` datetime DEFAULT NULL,
  `END_TIME` datetime NOT NULL,
  `CONTENT_CODE` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CHANNELCODESCHEDULEINDEX` (`CHANNEL_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='直播频道节目单表';

-- ----------------------------
-- Records of EPG_CONTENT_SCHEDULE
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CONTENT_SERIES
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CONTENT_SERIES`;
CREATE TABLE `EPG_CONTENT_SERIES` (
  `CONTENT_ID` bigint(20) NOT NULL COMMENT '记录标识',
  `CONTENT_CODE` varchar(128) DEFAULT NULL COMMENT '内容编码',
  `TITLE` varchar(256) DEFAULT NULL COMMENT '显示标题',
  `TITLE_BRIEF` varchar(256) DEFAULT NULL COMMENT '显示标题',
  `ENABLE_STATUS` int(2) DEFAULT NULL COMMENT '可用状态，只有连续剧中所有剧集可用后，连续剧才可用RN            0：不可用RN            1：可用',
  `EPISODE_NUMBER` int(8) NOT NULL DEFAULT '0' COMMENT '连续剧总集数',
  `PROVIDER` varchar(64) DEFAULT NULL COMMENT '提供商',
  `COUNTRY_OF_ORIGIN` varchar(64) DEFAULT NULL COMMENT '发行国家',
  `YEAR` varchar(20) DEFAULT NULL COMMENT '发行年份',
  `STUDIO` varchar(128) DEFAULT NULL COMMENT '发行公司',
  `PRODUCERS` varchar(128) DEFAULT NULL COMMENT '制片',
  `ACTORS` varchar(128) DEFAULT NULL COMMENT '演员',
  `DIRECTOR` varchar(128) DEFAULT NULL COMMENT '导演',
  `WRITER` varchar(128) DEFAULT NULL COMMENT '编剧',
  `SUMMARY_MEDIUM` varchar(1024) DEFAULT NULL COMMENT '内容简介',
  `SUMMARY_SHORT` varchar(1024) DEFAULT NULL COMMENT '内容看点',
  `CREATION_DATE` date DEFAULT NULL COMMENT '入库日期',
  `PROGRAM_LEVEL` int(2) DEFAULT NULL COMMENT '评分',
  `VOD_DUB` varchar(64) DEFAULT NULL COMMENT '配音',
  `VOD_CAPTION` varchar(64) DEFAULT NULL COMMENT '字幕',
  `KEY_WORD` varchar(256) DEFAULT NULL COMMENT '关键字',
  `REMARK` varchar(512) DEFAULT NULL COMMENT '备注',
  `RESERVE1` varchar(128) DEFAULT NULL,
  `RESERVE2` varchar(128) DEFAULT NULL,
  `RESERVE3` varchar(256) DEFAULT NULL,
  `RESERVE4` varchar(256) DEFAULT NULL,
  `RESERVE5` varchar(512) DEFAULT NULL,
  `ICON` varchar(512) DEFAULT NULL,
  `STILL` varchar(512) DEFAULT NULL,
  `POSTER` varchar(512) DEFAULT NULL,
  `SEARCH_NAME` varchar(128) DEFAULT NULL,
  `TAGS` varchar(128) DEFAULT NULL,
  `DISPLAY_RUN_TIME` varchar(8) DEFAULT NULL,
  `RUN_TIME` varchar(8) DEFAULT NULL,
  `MAIN_FOLDER` varchar(64) DEFAULT NULL,
  `SUB_FOLDER` varchar(64) DEFAULT NULL,
  `HD_TYPE` int(11) DEFAULT NULL,
  `REL_CODE` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`CONTENT_ID`),
  KEY `SERIESCODEINDEX` (`CONTENT_CODE`),
  KEY `SERIESSEARCHNAMEINDEX` (`SEARCH_NAME`),
  KEY `TITLE` (`TITLE`),
  KEY `CONTENT_ID` (`CONTENT_ID`),
  KEY `CONTENT_CODE` (`CONTENT_CODE`),
  KEY `ENABLE_STATUS` (`ENABLE_STATUS`),
  KEY `SEARCH_NAME` (`SEARCH_NAME`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='连续剧表';

-- ----------------------------
-- Records of EPG_CONTENT_SERIES
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CONTENT_VOTE
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CONTENT_VOTE`;
CREATE TABLE `EPG_CONTENT_VOTE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONTENT_TYPE` varchar(64) NOT NULL,
  `CONTENT_CODE` varchar(128) NOT NULL,
  `GOOD_COUNT` int(11) NOT NULL DEFAULT '0',
  `BAD_COUNT` int(11) NOT NULL DEFAULT '0',
  `SCORE` int(2) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='记录用户对内容进行顶踩打分的统计';

-- ----------------------------
-- Records of EPG_CONTENT_VOTE
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_CUSTOMER
-- ----------------------------
DROP TABLE IF EXISTS `EPG_CUSTOMER`;
CREATE TABLE `EPG_CUSTOMER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `GENDAR` int(11) DEFAULT NULL,
  `CUSTOMER_CODE` varchar(255) DEFAULT NULL,
  `ACCOUNT_ID` varchar(255) DEFAULT NULL,
  `BIRTHDAY` datetime DEFAULT NULL,
  `PHONENUMBER` varchar(255) DEFAULT NULL,
  `CUSTOMER_STATUS` int(11) DEFAULT NULL,
  `ICON` varchar(255) DEFAULT NULL,
  `BIG_ICON` varchar(255) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `RESERVE1` varchar(255) DEFAULT NULL,
  `RESERVE2` varchar(255) DEFAULT NULL,
  `RESERVE3` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3962 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of EPG_CUSTOMER
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_HOST_PROFILE
-- ----------------------------
DROP TABLE IF EXISTS `EPG_HOST_PROFILE`;
CREATE TABLE `EPG_HOST_PROFILE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `GROUP_ID` bigint(20) DEFAULT NULL,
  `HOST_CODE` varchar(128) DEFAULT NULL,
  `HOST_NAME` varchar(128) DEFAULT NULL,
  `HOST_IP` varchar(32) DEFAULT NULL,
  `NAME` varchar(128) DEFAULT NULL,
  `VALUE` varchar(128) DEFAULT NULL,
  `STATUS` int(2) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `HOSTPROFILEHOSTNAMEINDEX` (`HOST_NAME`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='主机配置';

-- ----------------------------
-- Records of EPG_HOST_PROFILE
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_POSITION
-- ----------------------------
DROP TABLE IF EXISTS `EPG_POSITION`;
CREATE TABLE `EPG_POSITION` (
  `ID` bigint(20) NOT NULL,
  `CODE` varchar(128) NOT NULL,
  `TYPE` varchar(32) DEFAULT NULL,
  `AD_CODE` varchar(128) DEFAULT NULL,
  `VALID_TIME` datetime DEFAULT NULL,
  `EXPIRE_TIME` datetime DEFAULT NULL,
  `WEIGHT` int(3) DEFAULT NULL,
  `OBJ_TYPE` varchar(32) NOT NULL COMMENT 'IMAGE：图片RN            VOD：点播视频RN            CHANNEL：直播视频RN            TEXT：文字',
  `OBJ_VALUE` varchar(128) NOT NULL,
  `LINK_OBJ_TYPE` varchar(31) DEFAULT NULL COMMENT 'VOD：点播视频RN            CHANNEL：直播视频RN            SUBJECT：专题RN            CATEGORY：栏目RN            TVBAR：看吧RN            URL：外部链接',
  `LINK_OBJ_VALUE` varchar(128) DEFAULT NULL,
  `DEFAULT_FLAG` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `POSITIONCODEINDEX` (`CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='推荐元素信息表';

-- ----------------------------
-- Records of EPG_POSITION
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_REL_CONTENT
-- ----------------------------
DROP TABLE IF EXISTS `EPG_REL_CONTENT`;
CREATE TABLE `EPG_REL_CONTENT` (
  `ID` bigint(20) NOT NULL,
  `REL_NAME` varchar(256) NOT NULL COMMENT '包名',
  `REL_CODE` varchar(128) NOT NULL COMMENT '包code',
  `CONTENT_CODE` varchar(128) NOT NULL COMMENT 'contentCode',
  `VIDEO_TYPE` int(2) DEFAULT NULL COMMENT '视频类型:0(HD),1(SD),2(3D)',
  `BODY_TYPE` int(2) DEFAULT NULL COMMENT '内容类型:1(正片),2(预告片),3(片花)',
  `AUDIO_TYPE` int(2) DEFAULT NULL COMMENT '声音类型:1(原声),2(国语),3(粤语)',
  `STATUS` int(2) DEFAULT '0' COMMENT '0(正常),1(删除)',
  `TYPE` varchar(50) DEFAULT NULL COMMENT '剧集:单剧集(vod),多剧集(series)',
  `REL_CODE_FLAG` int(2) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `REL_CODE` (`REL_CODE`),
  KEY `STATUS` (`STATUS`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of EPG_REL_CONTENT
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_SUBJECT_PAGE
-- ----------------------------
DROP TABLE IF EXISTS `EPG_SUBJECT_PAGE`;
CREATE TABLE `EPG_SUBJECT_PAGE` (
  `ID` bigint(20) NOT NULL,
  `SUBJECT_TITLE` varchar(128) DEFAULT NULL,
  `SUBJECT_CODE` varchar(128) DEFAULT NULL,
  `PAGE_NAME` varchar(128) NOT NULL,
  `PAGE_CODE` varchar(128) NOT NULL,
  `BACKGROUND` varchar(128) NOT NULL,
  `DEFAULT_FLAG` int(1) NOT NULL DEFAULT '0' COMMENT '0：不是RN            1：不是',
  `HIGH_DEFITION` varchar(32) DEFAULT NULL,
  `POSTER` varchar(128) DEFAULT NULL,
  `STILL` varchar(128) DEFAULT NULL,
  `ICON` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SUBJECTCODEINDEX` (`SUBJECT_CODE`),
  KEY `PAGECODEINDEX` (`PAGE_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='专题页面信息表';

-- ----------------------------
-- Records of EPG_SUBJECT_PAGE
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_SUBJECT_REGION
-- ----------------------------
DROP TABLE IF EXISTS `EPG_SUBJECT_REGION`;
CREATE TABLE `EPG_SUBJECT_REGION` (
  `ID` bigint(20) NOT NULL,
  `PAGE_CODE` varchar(64) DEFAULT NULL,
  `LOCATION` varchar(64) NOT NULL,
  `OBJ_TYPE` varchar(32) NOT NULL,
  `OBJ_CODE` varchar(128) NOT NULL,
  `DEFAULT_AREA` int(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `HOTAREAPAGECODEINDEX` (`PAGE_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='页面热区信息表';

-- ----------------------------
-- Records of EPG_SUBJECT_REGION
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_SUBSCRIBER
-- ----------------------------
DROP TABLE IF EXISTS `EPG_SUBSCRIBER`;
CREATE TABLE `EPG_SUBSCRIBER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ACCOUNT` varchar(128) NOT NULL COMMENT '用户帐号',
  `MAC_ADDRESS` varchar(64) DEFAULT NULL COMMENT 'MAC地址',
  `OSS_USER_ID` varchar(128) DEFAULT NULL COMMENT '外部标识',
  `USER_NAME` varchar(64) DEFAULT NULL COMMENT '用户名称',
  `ADDRESS` varchar(512) DEFAULT NULL COMMENT '家庭住址',
  `ZIP_CODE` varchar(10) DEFAULT NULL COMMENT '邮政编码',
  `PHONE_NUMBER` varchar(16) DEFAULT NULL COMMENT '联系电话',
  `EMAIL` varchar(128) DEFAULT NULL COMMENT '电子邮箱',
  `USER_GROUP` varchar(128) DEFAULT NULL COMMENT '用户组',
  `EXPLORE_NAME` varchar(128) DEFAULT NULL COMMENT '浏览器名',
  `EXPLORE_VERSION` varchar(128) DEFAULT NULL COMMENT '浏览器版本',
  `NETWORK_ID` varchar(8) DEFAULT NULL COMMENT '网络号,0001/0002',
  `STB_MODEL` varchar(128) DEFAULT NULL COMMENT '机顶盒型号',
  `STB_TYPE` varchar(8) DEFAULT NULL COMMENT '机顶盒类型,SD/HD',
  `RTSPD` varchar(8) DEFAULT NULL COMMENT 'RTSP_D 播放时使用,1 或其他',
  `PROTOCOL_TYPE` varchar(128) DEFAULT NULL COMMENT '协议类型,RTSP,HFC/RTSP,IP',
  PRIMARY KEY (`ID`),
  KEY `SUBSCRIBERUSERACCOUNTINDEX` (`USER_ACCOUNT`),
  KEY `SUBSCRIBERMACADDRESSINDEX` (`MAC_ADDRESS`),
  KEY `SUBSCRIBEROSSUSERIDINDEX` (`OSS_USER_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=20 DEFAULT CHARSET=utf8 COMMENT='订户信息表';

-- ----------------------------
-- Records of EPG_SUBSCRIBER
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_SUBSCRIBER_PPV
-- ----------------------------
DROP TABLE IF EXISTS `EPG_SUBSCRIBER_PPV`;
CREATE TABLE `EPG_SUBSCRIBER_PPV` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ACCOUNT` varchar(128) NOT NULL COMMENT '用户帐号',
  `USER_ID` varchar(128) NOT NULL,
  `USER_MAC` varchar(64) DEFAULT NULL COMMENT 'MAC地址',
  `BIZ_CODE` varchar(128) DEFAULT NULL COMMENT '看吧标识',
  `CATEGORY_CODE` varchar(128) DEFAULT NULL COMMENT '栏目标识',
  `CATEGORY_NAME` varchar(128) DEFAULT NULL COMMENT '栏目名称',
  `PROGRAM_CODE` varchar(128) NOT NULL COMMENT '内容标识',
  `PROGRAM_TITLE` varchar(128) NOT NULL COMMENT '内容名称',
  `OFFERINGID` varchar(128) NOT NULL COMMENT 'OFFERINGID',
  `SERVICENAME` varchar(128) DEFAULT NULL COMMENT 'SERVICENAME',
  `SERVICECODE` varchar(128) DEFAULT NULL COMMENT 'SERVICECODE',
  `SERVICETYPE` varchar(64) DEFAULT NULL COMMENT 'SERVICETYPE',
  `PROGRAM_TYPE` varchar(50) DEFAULT NULL COMMENT '影片类型',
  `PROTOCOL_TYPE` varchar(128) DEFAULT NULL COMMENT '使用场景',
  `PRICE` int(8) DEFAULT NULL COMMENT '单位：分',
  `ORDER_TIME` date DEFAULT NULL COMMENT '订购时间',
  `VALID_TIME` date DEFAULT NULL COMMENT '生效时间',
  `EXPIRE_TIME` date DEFAULT NULL COMMENT '失效时间',
  `FILE_NAME` varchar(256) DEFAULT NULL COMMENT '实体文件名',
  PRIMARY KEY (`ID`),
  KEY `SUBSCRIBERPPVMACFILENAMEINDEX` (`USER_MAC`,`FILE_NAME`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='按次点播订购列表';

-- ----------------------------
-- Records of EPG_SUBSCRIBER_PPV
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_TEMPLATE_BIND
-- ----------------------------
DROP TABLE IF EXISTS `EPG_TEMPLATE_BIND`;
CREATE TABLE `EPG_TEMPLATE_BIND` (
  `ID` bigint(20) NOT NULL,
  `BIZ_CODE` varchar(128) NOT NULL,
  `CATEGORY_CODE` varchar(128) DEFAULT NULL,
  `LOCATE_STR` varchar(256) DEFAULT NULL,
  `CONTENT_TYPE` varchar(32) DEFAULT NULL COMMENT '一个栏目或一个看吧下可以绑定多个详细页面模板，按内容类型进行区分',
  `TEMPLATE_TYPE` varchar(32) NOT NULL,
  `TEMPLATE_CODE` varchar(128) NOT NULL,
  `TMP_PACK_CODE` varchar(128) NOT NULL,
  `TEMPLATE_PATH` varchar(128) DEFAULT NULL COMMENT '模板文件相对于模板包所在目录的路径',
  `TEMPLATE_PARAMS` varchar(2000) DEFAULT NULL COMMENT '格式：RN            参数名1=参数类型1=参数值1|参数名2=参数类型2=参数值2|......',
  PRIMARY KEY (`ID`),
  KEY `TEMPBINDBIZCODEINDEX` (`BIZ_CODE`),
  KEY `TEMPBINDCATCODEINDEX` (`CATEGORY_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of EPG_TEMPLATE_BIND
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_USER_BOOKMARK
-- ----------------------------
DROP TABLE IF EXISTS `EPG_USER_BOOKMARK`;
CREATE TABLE `EPG_USER_BOOKMARK` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(128) NOT NULL,
  `CONTENT_NAME` varchar(128) NOT NULL,
  `CONTENT_TYPE` varchar(32) NOT NULL,
  `CONTENT_CODE` varchar(128) NOT NULL,
  `CONTENT_ELAPSED` int(8) NOT NULL,
  `MARK_TIME` datetime NOT NULL,
  `BIZ_CODE` varchar(128) DEFAULT NULL,
  `CATEGORY_CODE` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `bookmarkUserIdIndex` (`USER_ID`),
  KEY `bookmarkContentCodeIndex` (`CONTENT_CODE`)
) ENGINE=MyISAM AUTO_INCREMENT=5757 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of EPG_USER_BOOKMARK
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_USER_COLLECTION
-- ----------------------------
DROP TABLE IF EXISTS `EPG_USER_COLLECTION`;
CREATE TABLE `EPG_USER_COLLECTION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(128) NOT NULL,
  `CONTENT_NAME` varchar(128) NOT NULL,
  `CONTENT_TYPE` varchar(32) NOT NULL,
  `CONTENT_CODE` varchar(128) NOT NULL,
  `COLLECT_TIME` date NOT NULL,
  `BIZ_CODE` varchar(128) DEFAULT NULL,
  `CATEGORY_CODE` varchar(128) DEFAULT NULL,
  `STILL` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `COLLECTIONUSERIDINDEX` (`USER_ID`),
  KEY `COLLECTIONCONTENTCODEINDEX` (`CONTENT_CODE`)
) ENGINE=MyISAM AUTO_INCREMENT=659 DEFAULT CHARSET=utf8 COMMENT='用户内容收藏记录';

-- ----------------------------
-- Records of EPG_USER_COLLECTION
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_USER_HISTORY
-- ----------------------------
DROP TABLE IF EXISTS `EPG_USER_HISTORY`;
CREATE TABLE `EPG_USER_HISTORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(128) DEFAULT NULL,
  `CONTENT_NAME` varchar(128) DEFAULT NULL,
  `CONTENT_TYPE` varchar(32) DEFAULT NULL,
  `CONTENT_CODE` varchar(128) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `BIZ_CODE` varchar(128) DEFAULT NULL,
  `CATEGORY_CODE` varchar(128) DEFAULT NULL,
  `SERIES_CODE` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `HISTORYCONTENTCODEINDEX` (`CONTENT_CODE`),
  KEY `HISTORYUSERIDINDEX` (`USER_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=357 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of EPG_USER_HISTORY
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_USER_SERIESMARK
-- ----------------------------
DROP TABLE IF EXISTS `EPG_USER_SERIESMARK`;
CREATE TABLE `EPG_USER_SERIESMARK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(256) DEFAULT NULL,
  `CONTENT_CODE` varchar(256) DEFAULT NULL,
  `EPISODE_INDEX` int(5) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=524 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of EPG_USER_SERIESMARK
-- ----------------------------

-- ----------------------------
-- Table structure for EPG_VOTE_RECORD
-- ----------------------------
DROP TABLE IF EXISTS `EPG_VOTE_RECORD`;
CREATE TABLE `EPG_VOTE_RECORD` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_MAC` varchar(50) NOT NULL,
  `CONTENT_TYPE` varchar(64) NOT NULL,
  `CONTENT_CODE` varchar(128) NOT NULL,
  `VOTE_METHOD` varchar(50) NOT NULL,
  `VOTE_VAL` int(2) NOT NULL,
  `VOTE_TIME` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='记录用户进行投票的操作记录';

-- ----------------------------
-- Records of EPG_VOTE_RECORD
-- ----------------------------
DROP TRIGGER IF EXISTS `INSERT_PROGRAM_TRIGGER`;
DELIMITER ;;
CREATE TRIGGER `INSERT_PROGRAM_TRIGGER` AFTER INSERT ON `EPG_CONTENT_PROGRAM` FOR EACH ROW BEGIN
INSERT INTO CONTENT_WITH_PIC(`CONTENT_ID`, `CONTENT_CODE`, `TITLE`, `TITLE_BRIEF`, `ENABLE_STATUS`, `COUNTRY_OF_ORIGIN`, `YEAR`, `VOD_DUB`, `VOD_CAPTION`, `DIRECTOR`, `ACTORS`, `SUMMARY_MEDIUM`, `SUMMARY_SHORT`, `KEY_WORD`, `REMARK`, `PROGRAM_LEVEL`, `RESERVE1`, `CREATION_DATE`, `POSTER`, `STILL`, `ICON`, `EPISODE_NUMBER`, `SEARCH_NAME`, `RUN_TIME`, `DISPLAY_RUN_TIME`, `CONTENT_TYPE`, `PROGRAM_TYPE`, `PROVIDER`, `PRODUCT`, `SUGGESTED_PRICE`, `TITLE_TYPE`, `ASSETID`, `TAGS`, `MAIN_FOLDER`, `HD_TYPE`, `REL_CODE`) VALUES(NEW.CONTENT_ID,NEW.CONTENT_CODE,NEW.TITLE,NEW.TITLE_BRIEF,NEW.ENABLE_STATUS,NEW.COUNTRY_OF_ORIGIN,NEW.YEAR,NEW.VOD_DUB,NEW.VOD_CAPTION,NEW.DIRECTOR,NEW.ACTORS,NEW.SUMMARY_MEDIUM,NEW.SUMMARY_SHORT,NEW.KEY_WORD,NEW.REMARK,NEW.PROGRAM_LEVEL,NEW.RESERVE1,NEW.CREATION_DATE,NEW.POSTER,NEW.STILL,NEW.ICON,1,NEW.SEARCH_NAME,NEW.RUN_TIME,NEW.DISPLAY_RUN_TIME,'VOD',NEW.TYPE,NEW.PROVIDER,NEW.PRODUCT,NEW.SUGGESTED_PRICE,NEW.TITLE_TYPE,NEW.ASSETID,NEW.TAGS,NEW.MAIN_FOLDER,NEW.HD_TYPE,NEW.REL_CODE );
 
END
;;
DELIMITER ;
DROP TRIGGER IF EXISTS `UPDATE_PROGRAM_TRIGGER`;
DELIMITER ;;
CREATE TRIGGER `UPDATE_PROGRAM_TRIGGER` AFTER UPDATE ON `EPG_CONTENT_PROGRAM` FOR EACH ROW BEGIN
UPDATE CONTENT_WITH_PIC SET `CONTENT_CODE`=NEW.CONTENT_CODE, `TITLE`=NEW.TITLE, `TITLE_BRIEF`=NEW.TITLE_BRIEF, `ENABLE_STATUS`=NEW.ENABLE_STATUS, `COUNTRY_OF_ORIGIN`=NEW.COUNTRY_OF_ORIGIN, `YEAR`=NEW.YEAR, `VOD_DUB`=NEW.VOD_DUB, `VOD_CAPTION`=NEW.VOD_CAPTION, `DIRECTOR`=NEW.DIRECTOR, `ACTORS`=NEW.ACTORS, `SUMMARY_MEDIUM`=NEW.SUMMARY_MEDIUM, `SUMMARY_SHORT`=NEW.SUMMARY_SHORT, `KEY_WORD`=NEW.KEY_WORD, `REMARK`=NEW.REMARK, `PROGRAM_LEVEL`=NEW.PROGRAM_LEVEL, `RESERVE1`=NEW.RESERVE1, `CREATION_DATE`=NEW.CREATION_DATE, `POSTER`=NEW.POSTER, `STILL`=NEW.STILL, `ICON`=NEW.ICON, `EPISODE_NUMBER`=1, `SEARCH_NAME`=NEW.SEARCH_NAME, `RUN_TIME`=NEW.RUN_TIME, `DISPLAY_RUN_TIME`=NEW.DISPLAY_RUN_TIME, `CONTENT_TYPE`='VOD', `PROGRAM_TYPE`=NEW.TYPE, `PROVIDER`=NEW.PROVIDER, `PRODUCT`=NEW.PRODUCT, `SUGGESTED_PRICE`=NEW.SUGGESTED_PRICE, `TITLE_TYPE`=NEW.TITLE_TYPE, `ASSETID`=NEW.ASSETID, `TAGS`=NEW.TAGS, `MAIN_FOLDER`=NEW.MAIN_FOLDER ,  `SUB_FOLDER`=NEW.SUB_FOLDER WHERE `CONTENT_ID` = NEW.CONTENT_ID;
END
;;
DELIMITER ;
DROP TRIGGER IF EXISTS `DELETE_PROGRAM_TRIGGER`;
DELIMITER ;;
CREATE TRIGGER `DELETE_PROGRAM_TRIGGER` AFTER DELETE ON `EPG_CONTENT_PROGRAM` FOR EACH ROW BEGIN
DELETE FROM CONTENT_WITH_PIC WHERE `CONTENT_ID` = OLD.CONTENT_ID;
 
END
;;
DELIMITER ;
DROP TRIGGER IF EXISTS `INSERT_SERIES_TRIGGER`;
DELIMITER ;;
CREATE TRIGGER `INSERT_SERIES_TRIGGER` AFTER INSERT ON `EPG_CONTENT_SERIES` FOR EACH ROW BEGIN
INSERT INTO CONTENT_WITH_PIC(`CONTENT_ID`, `CONTENT_CODE`, `TITLE`, `TITLE_BRIEF`, `ENABLE_STATUS`, `COUNTRY_OF_ORIGIN`, `YEAR`, `VOD_DUB`, `VOD_CAPTION`, `DIRECTOR`, `ACTORS`, `SUMMARY_MEDIUM`, `SUMMARY_SHORT`, `KEY_WORD`, `REMARK`, `PROGRAM_LEVEL`, `RESERVE1`, `CREATION_DATE`, `POSTER`, `STILL`, `ICON`, `EPISODE_NUMBER`, `SEARCH_NAME`, `RUN_TIME`, `DISPLAY_RUN_TIME`, `CONTENT_TYPE`, `PROGRAM_TYPE`, `PROVIDER`, `PRODUCT`, `SUGGESTED_PRICE`, `TITLE_TYPE`, `TAGS`, `MAIN_FOLDER`, `SUB_FOLDER`) VALUES(NEW.CONTENT_ID,NEW.CONTENT_CODE,NEW.TITLE,NEW.TITLE_BRIEF,NEW.ENABLE_STATUS,NEW.COUNTRY_OF_ORIGIN,NEW.YEAR,NEW.VOD_DUB,NEW.VOD_CAPTION,NEW.DIRECTOR,NEW.ACTORS,NEW.SUMMARY_MEDIUM,NEW.SUMMARY_SHORT,NEW.KEY_WORD,NEW.REMARK,NEW.PROGRAM_LEVEL,NEW.RESERVE1,NEW.CREATION_DATE,NEW.POSTER,NEW.STILL,NEW.ICON,NEW.EPISODE_NUMBER,NEW.SEARCH_NAME,NULL,NULL,'SERIES','SERIES',NEW.PROVIDER,NULL,0,'VOD',NEW.TAGS,NEW.MAIN_FOLDER,NEW.SUB_FOLDER);
 
END
;;
DELIMITER ;
DROP TRIGGER IF EXISTS `UPDATE_SERIES_TRIGGER`;
DELIMITER ;;
CREATE TRIGGER `UPDATE_SERIES_TRIGGER` AFTER UPDATE ON `EPG_CONTENT_SERIES` FOR EACH ROW BEGIN
UPDATE CONTENT_WITH_PIC SET `CONTENT_CODE`=NEW.CONTENT_CODE, `TITLE`=NEW.TITLE, `TITLE_BRIEF`=NEW.TITLE_BRIEF, `ENABLE_STATUS`=NEW.ENABLE_STATUS, `COUNTRY_OF_ORIGIN`=NEW.COUNTRY_OF_ORIGIN, `YEAR`=NEW.YEAR, `VOD_DUB`=NEW.VOD_DUB, `VOD_CAPTION`=NEW.VOD_CAPTION, `DIRECTOR`=NEW.DIRECTOR, `ACTORS`=NEW.ACTORS, `SUMMARY_MEDIUM`=NEW.SUMMARY_MEDIUM, `SUMMARY_SHORT`=NEW.SUMMARY_SHORT, `KEY_WORD`=NEW.KEY_WORD, `REMARK`=NEW.REMARK, `PROGRAM_LEVEL`=NEW.PROGRAM_LEVEL, `RESERVE1`=NEW.RESERVE1, `CREATION_DATE`=NEW.CREATION_DATE, `POSTER`=NEW.POSTER, `STILL`=NEW.STILL, `ICON`=NEW.ICON, `EPISODE_NUMBER`=NEW.EPISODE_NUMBER, `SEARCH_NAME`=NEW.SEARCH_NAME, `RUN_TIME`=NULL, `DISPLAY_RUN_TIME`=NULL, `CONTENT_TYPE`='SERIES', `PROGRAM_TYPE`='SERIES', `PROVIDER`=NEW.PROVIDER, `PRODUCT`=NULL, `SUGGESTED_PRICE`=0, `TITLE_TYPE`='VOD', `TAGS`=NEW.TAGS, `MAIN_FOLDER`=NEW.MAIN_FOLDER, `SUB_FOLDER`=NEW.SUB_FOLDER  WHERE `CONTENT_ID` = NEW.CONTENT_ID;
 
END
;;
DELIMITER ;
DROP TRIGGER IF EXISTS `DELETE_SERIES_TRIGGER`;
DELIMITER ;;
CREATE TRIGGER `DELETE_SERIES_TRIGGER` AFTER DELETE ON `EPG_CONTENT_SERIES` FOR EACH ROW BEGIN
DELETE FROM CONTENT_WITH_PIC WHERE `CONTENT_ID` = OLD.CONTENT_ID;
END
;;
DELIMITER ;
